// Loading Types
export const USER_LOADING_ATTEMPT = "USER_LOADING_ATTEMPT"
export const USER_LOADING_TRUE = "USER_LOADING_TRUE"
export const USER_LOADING_FALSE = "USER_LOADING_FALSE"

//USER TYPES
export const USER_LOGIN = "USER_LOGIN"
export const USER_LOAD = "USER_LOAD"
export const USER_FORGET_PASSWORD = "USER_FORGET_PASSWORD"
export const USER_COMPLAINT = "USER_COMPLAINT"
export const USER_COMPLAINT_CLIENT = "USER_COMPLAINT_CLIENT"